[package]
name = "selfsync-proto"
description = "Сгенерированные типы протокола selfsync v1"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
prost.workspace = true

[build-dependencies]
prost-build.workspace = true
protox.workspace = true
